apiVersion: v1
kind: Pod
metadata: { name: debug, namespace: iris, labels: { use: debug } }
spec:
  restartPolicy: Never
  containers:
    - name: debug
      image: nicolaka/netshoot:latest
      command: ["sleep", "infinity"]
