{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "iris-api.fullname" . }}
  labels: {{- include "iris-api.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - { path: /, pathType: Prefix, backend: { service: { name: {{ include "iris-api.fullname" . }}, port: { name: http } } } }
  {{- if .Values.ingress.tls }}
  tls:
    - hosts: [{{ .Values.ingress.host }}]
      secretName: {{ include "iris-api.fullname" . }}-tls
  {{- end }}
{{- end }}
